[package]
name = "bls"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

build = "build.rs"

[dependencies]
eth2_ssz = "0.1.2"
tree_hash = "0.1.0"
milagro_bls = { git = "https://github.com/sigp/milagro_bls", tag = "v1.1.0" }
rand = "0.7.2"
serde = "1.0.102"
serde_derive = "1.0.102"
serde_hex = { path = "../../consensus/serde_hex" }
hex = "0.3"
eth2_hashing = "0.1.0"
ethereum-types = "0.8.0"
arbitrary = { version = "0.4.4", features = ["derive"], optional = true }

[features]
default = ["milagro"]
fake_crypto = []
milagro = []
herumi = []
